name: ElectricFloor
version: ALPHA-1.0.1
author: SunStorm
description: An amazing event plugin
main: me.electricfloor.main.ElectricFloor
softdepend: [WorldEdit, Essentials]

commands:
    electricfloor:
        usage: /<command>
        aliases: [ef]
        description: Main command.
    event:
        usage: /<command>
        description: Event management.
#    eventnpc:
#        usage: /<command>
#        description: Npc management.
permissions:
    electricfloor.admin:
        default: op
        description: All rights
        children:
            electricfloor.event.bc: true
            electricfloor.event.start: true
            electricfloor.event.stop: true
            electricfloor.event.kick: true
            electricfloor.event.join: true
            electricfloor.event.leave: true
            electricfloor.set.wait: true
            electricfloor.set.arena: true
            electricfloor.set.loss: true
            electricfloor.set.spawn: true
            electricfloor.set.start: true
            electricfloor.set.win1: true
            electricfloor.set.win2: true
            electricfloor.set.win3: true
            electricfloor.reload: true
    electricfloor.player:
        default: true
        description: Player rights
        children:
            electricfloor.event.join: true
            electricfloor.event.leave: true
    electricfloor.settings:
        default: false
        description: Event config
        children:
            electricfloor.set.wait: true
            electricfloor.set.arena: true
            electricfloor.set.loss: true
            electricfloor.set.start: true
            electricfloor.set.spawn: true
            electricfloor.set.win1: true
            electricfloor.set.win2: true
            electricfloor.set.win3: true
            electricfloor.player: true
    electricfloor.event:
        default: false
        description: Event control
        children:
            electricfloor.event.bc: true
            electricfloor.event.start: true
            electricfloor.event.stop: true
            electricfloor.event.kick: true
            electricfloor.event.join: true
            electricfloor.event.leave: true
    electricfloor.event.bc:
        default: false
        description: Event broadcast
    electricfloor.event.start:
        default: false
        description: Event start
    electricfloor.event.stop:
        default: false
        description: Event stop
    electricfloor.event.kick:
        default: false
        description: Kick a player
    electricfloor.event.join:
        default: false
        description: Join to the event
    electricfloor.event.leave:
        default: false
        description: Leave the event
    electricfloor.event.create:
        default: false
        description: Create a new event, without any config
    electricfloor.event.delete:
        default: false
        description: Delete an event
    electricfloor.set.lobby:
        default: false
        description: Set lobby
    electricfloor.set.arena:
        default: false
        description: Set the arena
    electricfloor.set.lost:
        default: false
        description: Set the loosers place
    electricfloor.set.spawn:
        default: false
        description: Set the spawn, for the teleportation at the event
    electricfloor.set.win1:
        default: false
        description: Set the 1st player pace
    electricfloor.set.win2:
        default: false
        description: Set the 2nd player pace
    electricfloor.set.win3:
        default: false
        description: Set the 3rd player pace
    electricfloor.reload:
        default: false
        description: Plugin reload
    
            
            